spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: my_app_db
      username: mongo
      password: mongo
      authentication-database: "admin"

logging:
  level:
    com:
      example: INFO
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG